# Prompt Reviewer Persona
# Spawned to review and suggest updates to CLAUDE.md based on epistemic state

name: prompt_reviewer
description: Reviews system prompts against epistemic findings and suggests updates

# When to spawn this persona
triggers:
  - after_postflight_with_high_impact_finding  # impact >= 0.8
  - on_calibration_drift_detected
  - manual_request

# Initial vector profile (starts skeptical)
initial_vectors:
  know: 0.4
  uncertainty: 0.7
  context: 0.5
  clarity: 0.6

# Task template
task_template: |
  Review the system prompt (CLAUDE.md) against recent epistemic findings.

  ## Instructions
  1. Read ~/.claude/CLAUDE.md
  2. Query recent high-impact findings: empirica project-bootstrap --output json
  3. Compare prompt claims against findings evidence
  4. Identify gaps where:
     - Prompt describes behavior that findings contradict
     - Findings reveal patterns not captured in prompt
     - Calibration data suggests different thresholds
  5. Propose minimal, precise edits (not rewrites)

  ## Output
  - List of suggested edits with rationale
  - Each edit should cite the finding that motivates it
  - Prioritize by impact

# Convergence criteria
convergence:
  threshold: 0.03
  max_loops: 3
  success_indicator: suggested_edits_or_no_changes_needed

# Scope constraints
scope:
  breadth: 0.2  # Narrow - just CLAUDE.md
  duration: 0.1  # Quick - single review pass
  coordination: 0.0  # Solo task
